import { PostProps } from "@/components/types";

export let posts: PostProps[] = [
  // {
  //   contentType: "Research",
  //   slug: "viewdelta-text-prompted-change-detection-in-unaligned-images",
  //   thumbnail: "/assets/projects/2025/viewDelta/thumbnail.png",
  //   title: "ViewDelta: Text-Prompted Change Detection in Unaligned Images",
  //   authors: ["Subin Varghese", "Joshua Gao", "Vedhus Hoskere"],
  //   journal: "ICCV 2025",
  //   journalHighlighted: false,
  //   description: `Can you spot the difference between these two images? ViewDelta can! We show you how ViewDelta solves text-prompted change detection in many domains.`,
  //   date: "Nov 2025",
  //   claps: undefined,
  //   views:undefined,
  //   // link: "https://joshuakgao.github.io/viewdelta/",
  //   tags: ["Research Paper", "AI"],
  //   year: "2025",
  // },
  {
    contentType: "Project",
    slug: "self-hosted-cloud-storage",
    thumbnail: "/assets/projects/2024/self-hosted-cloud-storage/thumbnail.jpg",
    title: "Self Hosted NextCloud Is Game Changing",
    description:
      "All it takes to avoid Google Drive and DropBox subscriptions is a RasberryPi and NextCloud.",
    links: { website: "https://cloud.joshgao.com" },
    date: "Dec 2024",
    claps: undefined,
    views: undefined,
    tags: ["Hardware"],
    year: "2024",
  },
  // {
  //   contentType: "Project",
  //   slug: "how-do-you-do-change-detection-on-unaligned-images-heres-how",
  //   title: "How Do You Do Change Detection on Unaligned Images? Here's how.",
  //   description:
  //     "We leverage the power of vision LLMs and HLoc to do just that.",
  //   thumbnail: "/assets/images/cat.jpeg",
  //   // link: "https://github.com/tugonbob/reddit-laughs",
  //   date: "Nov 2024",
  //   claps: undefined,
  //   views: undefined,
  //   tags: ["AI"],
  //   year: "2024",
  // },
  // {
  //   contentType: "Project",
  //   slug: "tired-of-writing-inspection-reports-let-ai-do-it",
  //   title: "Tired of Writing Inspection Reports? Let AI Do It!",
  //   description:
  //     "We utilize the power of LLMs, computer vision, and change detection to automate the process of writing engineering inspection reports. Say goodbye to tedious manual work and hello to efficiency!",
  //   thumbnail: "/assets/projects/2025/viewDelta/thumbnail.png",
  //   // link: "https://github.com/tugonbob/reddit-laughs",
  //   date: "Sep 2024",
  //   year: "2024",
  //   claps: undefined,
  //   views: undefined,
  //   tags: ["AI"],
  // },
  // {
  //   contentType: "Project",
  //   slug: "how-do-you-find-duplicate-images-despite-different-views-and-time-taken-hloc-might-help",
  //   title:
  //     "How do you find duplicate images despite different views and time taken? HLoc might help.",
  //   description:
  //     "Think two photos are totally different? Think again. Discover how HLoc uncovers duplicates hiding in plain sight—even when angles, lighting, or backgrounds change.",
  //   thumbnail: "/assets/images/cat.jpeg",
  //   // link: "https://github.com/tugonbob/reddit-laughs",
  //   date: "Sep 2024",
  //   year: "2024",
  //   claps: undefined,
  //   views: undefined,
  //   tags: ["AI"],
  // },
  // {
  //   contentType: "Project",
  //   slug: "gptnano-beating-openais-gpt-2",
  //   title: "GptNano: Beating OpenAI's GPT-2",
  //   description:
  //     "Who says size matters? Meet GptNano: the pint-sized powerhouse that outsmarts GPT-2 without breaking a sweat (or your GPU). Find out how this tiny titan is punching way above its weight.",
  //   thumbnail: "/assets/projects/2024/gptNano/thumbnail.jpeg",
  //   date: "May 2024",
  //   year: "2024",
  //   // link: "https://github.com/tugonbob/gpt-nano",
  //   claps: undefined,
  //   views: undefined,
  //   tags: ["AI"],
  // },
  // {
  //   contentType: "Project",
  //   slug: "knn-image-classification",
  //   title: "KNN Image Classification",
  //   description: "A KNN image classifier trained on CIFAR-10 dataset.",
  //   thumbnail: "/assets/images/cat.jpeg",
  //   date: "2023",
  //   year: "2023",
  //   // link: "https://github.com/tugonbob/cifar-knn-classifer",
  //   claps: undefined,
  //   views: undefined,
  //   tags: ["AI"],
  // },
  // {
  //   contentType: "Project",
  //   slug: "how-much-is-your-home-worth-we-optimized-amachine-learning-model",
  //   title: "How Much Is Your Home Worth? We Optimized a Machine Learning Model",
  //   description:
  //     "A machine learning model trained on Zillow data with multi variable stochastic gradient descent.",
  //   thumbnail: "/assets/projects/2023/realEstateValuation/thumbnail.mp4",
  //   date: "Jun 2023",
  //   year: "2023",
  //   // link: "https://github.com/tugonbob/stanford-cs229-andrew-ng/blob/main/Ch1-SupervisedLearning/1-LinearRegression/1.1.1-LmsAlgorithm.ipynb",
  //   claps: undefined,
  //   views: undefined,
  //   tags: ["AI"],
  // },
  // {
  //   contentType: "Project",
  //   slug: "auto-youtube",
  //   title: "Auto Youtube",
  //   date: "2022",
  //   year: "2022",
  //   // link: "https://github.com/tugonbob/reddit-laughs",
  //   thumbnail: "/assets/projects/2023/realEstateValuation/thumbnail.mp4",
  //   claps: undefined,
  //   views: undefined,
  //   tags: ["Other"],
  // },
  {
    contentType: "Project",
    slug: "stock-portfolio-tracker",
    title: "How to Track Your Stock Portfolio with Google Sheets",
    date: "Dec 2022",
    year: "2022",
    thumbnail: "/assets/projects/2022/stock-portfolio-tracker/thumbnail.png",
    claps: undefined,
    views: undefined,
    tags: ["Other"],
    links: {
      googleDrive:
        "https://docs.google.com/spreadsheets/d/1wrPfNQtEmuMB3GUdjDgKffgdOIyPkrvQC0l_QhYNKxE/edit?usp=sharing",
    },
  },
];
